<a href="https://colab.research.google.com/github/asennakesavan/kesavan_code/blob/master/Day12_python_10_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [97]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("/content/sql_army.db")

In [98]:
army = pd.read_sql("select * from army_table",conn)

In [99]:
conn.close()

In [100]:
army.head()

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,4,Dragoons,1st,43,4,1592,73,2,0,3,Maine

In [10]:
army.shape
rows = army.shape[0]
Columns = army.shape[1]

In [11]:
print(f"The army dataset has {rows} rows and {Columns} Columns")

The army dataset has 12 rows and 11 Columns

In [15]:
army.dtypes

index         int64
regiment     object
company      object
deaths        int64
battles       int64
size          int64
veterans      int64
readiness     int64
armored       int64
deserters     int64
origin       object
dtype: object

To get unique value for all the columns

In [27]:
for i in army.columns:
  print(i,army[i].nunique(),"-->",army[i].unique())

index 12 --> [ 0  1  2  3  4  5  6  7  8  9 10 11]
regiment 3 --> ['Nighthawks' 'Dragoons' 'Scouts']
company 2 --> ['1st' '2nd']
deaths 10 --> [523  52  25 616  43 234  62  73  37  35]
battles 8 --> [ 5 42  2  4  7  8  3  9]
size 11 --> [1045  957 1099 1400 1592 1006  987  849  973 1005 1523]
veterans 11 --> [  1   5  62  26  73  37 949  48 435  63 345]
readiness 3 --> [1 2 3]
armored 2 --> [1 0]
deserters 5 --> [ 4 24 31  2  3]
origin 12 --> ['Arizona' 'California' 'Texas' 'Florida' 'Maine' 'Iowa' 'Alaska'
 'Washington' 'Oregon' 'Wyoming' 'Louisana' 'Georgia']

In [29]:
army.loc[army['deserters']>=10,:]

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
1,1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
6,6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,7,Dragoons,2nd,62,3,849,48,3,1,31,Washington

In [30]:
army[army['deserters']>=10]

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
1,1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
6,6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,7,Dragoons,2nd,62,3,849,48,3,1,31,Washington

In [32]:
army[army.deserters>=10]

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
1,1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
6,6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,7,Dragoons,2nd,62,3,849,48,3,1,31,Washington

In [36]:
army.loc[army['deserters']>=10,['regiment','origin']]

     regiment      origin
1  Nighthawks  California
2  Nighthawks       Texas
6    Dragoons      Alaska
7    Dragoons  Washington

In [40]:
army[['regiment','deaths']].groupby('regiment').sum()

            deaths
regiment
Dragoons       862
Nighthawks    1216
Scouts         207

In [43]:
army[['regiment','origin','deaths']].groupby(['regiment','origin']).sum()

                       deaths
regiment   origin
Dragoons   Alaska         523
           Iowa           234
           Maine           43
           Washington      62
Nighthawks Arizona        523
           California      52
           Florida        616
           Texas           25
Scouts     Georgia         35
           Louisana        37
           Oregon          62
           Wyoming         73

In [45]:
army[army['deserters']>10]

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
1,1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
6,6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,7,Dragoons,2nd,62,3,849,48,3,1,31,Washington

In [48]:
army.query('deserters > 10')

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
1,1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
6,6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,7,Dragoons,2nd,62,3,849,48,3,1,31,Washington

In [50]:
army.query('size>1000')[['regiment','deaths']]

      regiment  deaths
0   Nighthawks     523
2   Nighthawks      25
3   Nighthawks     616
4     Dragoons      43
5     Dragoons     234
9       Scouts      73
10      Scouts      37
11      Scouts      35

In [67]:
army.query(('size>1000 & readiness==3'))[['regiment','size','readiness']]

      regiment  size  readiness
2   Nighthawks  1099          3
3   Nighthawks  1400          3
11      Scouts  1523          3

In [65]:
army.loc[(army['size']>1000) & (army['readiness']==3),['regiment','size','readiness']]

      regiment  size  readiness
2   Nighthawks  1099          3
3   Nighthawks  1400          3
11      Scouts  1523          3

In [95]:
army

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
6,6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska

In [71]:
army.query('deaths>500 & battles>=5').sort_values('battles',ascending=False)

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
6,6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
0,0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona

In [75]:
army.loc[(army['deaths']>500) & (army['battles']>=5)].sort_values('battles',ascending=False)

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
6,6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
0,0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona

In [78]:
army.loc[(army['deaths']>500) & (army['battles']>=5),['regiment','company','deaths','battles']].sort_values('battles',ascending=False)

     regiment company  deaths  battles
6    Dragoons     2nd     523        8
0  Nighthawks     1st     523        5

In [81]:
army[(army['deaths']>500) & (army['battles']>=5)].sort_values('battles',ascending=False)[['regiment','company','deaths','battles']]

     regiment company  deaths  battles
6    Dragoons     2nd     523        8
0  Nighthawks     1st     523        5

In [86]:
army.query('deaths>500 & battles>=5').sort_values('battles',ascending=False)[['regiment','company','deaths','battles']]

     regiment company  deaths  battles
6    Dragoons     2nd     523        8
0  Nighthawks     1st     523        5

In [91]:
noc = 500
army.query('deaths>@noc & battles>=5',inplace=True).sort_values('battles',ascending=False)[['regiment','company','deaths','battles']]

AttributeError: 'NoneType' object has no attribute 'sort_values'

In [90]:
noc = 500
army[(army['deaths']>noc) & (army['battles']>=5)].sort_values('battles',ascending=False)[['regiment','company','deaths','battles']]

     regiment company  deaths  battles
6    Dragoons     2nd     523        8
0  Nighthawks     1st     523        5

In [102]:
army.query('origin == "California" | origin == "Alaska"')

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
1,1,Nighthawks,1st,52,42,957,5,2,0,24,California
6,6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska

In [104]:
States = ['California','Alaska','Texas']
army[army['origin'].isin(States)]

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
1,1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
6,6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska

In [106]:
army[['regiment','deaths']].groupby('regiment').agg(['mean','max','min','sum'])

            deaths
              mean  max min   sum
regiment
Dragoons    215.50  523  43   862
Nighthawks  304.00  616  25  1216
Scouts       51.75   73  35   207

In [108]:

army.groupby(['regiment']).sum(numeric_only=True)

,index,deaths,battles,size,veterans,readiness,armored,deserters
regiment,,,,,,,,
Dragoons,22,862,22,4434,1107,8,2,62
Nighthawks,6,1216,51,4501,94,9,3,61
Scouts,38,207,28,4600,891,8,2,10

In [114]:
army[['regiment','size','veterans']].groupby('regiment').agg('max')

            size  veterans
regiment
Dragoons    1592       949
Nighthawks  1400        62
Scouts      1523       435

In [115]:
army.groupby('regiment').max()['veterans']

regiment
Dragoons      949
Nighthawks     62
Scouts        435
Name: veterans, dtype: int64

In [117]:
army.groupby('regiment').sum()['size']

regiment
Dragoons      4434
Nighthawks    4501
Scouts        4600
Name: size, dtype: int64

In [118]:
army.groupby('regiment').max()['veterans'].sum()['size']

IndexError: invalid index to scalar variable.

In [119]:
army.groupby('regiment').agg(
    Tot_troops =('deaths','sum'),
    Max_Vet =('veterans','max'))

            Tot_troops  Max_Vet
regiment
Dragoons           862      949
Nighthawks        1216       62
Scouts             207      435

In [125]:
army

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,0,Nighthawks,1st,523,5,1045,1,1,1,4,Arizona
1,1,Nighthawks,1st,52,42,957,5,2,0,24,California
2,2,Nighthawks,2nd,25,2,1099,62,3,1,31,Texas
3,3,Nighthawks,2nd,616,2,1400,26,3,1,2,Florida
4,4,Dragoons,1st,43,4,1592,73,2,0,3,Maine
5,5,Dragoons,1st,234,7,1006,37,1,1,4,Iowa
6,6,Dragoons,2nd,523,8,987,949,2,0,24,Alaska
7,7,Dragoons,2nd,62,3,849,48,3,1,31,Washington
8,8,Scouts,1st,62,4,973,48,2,0,2,Oregon
9,9,Scouts,1st,73,7,1005,435,1,0,3,Wyoming
10,10,Scouts,2nd,37,8,1099,63,2,1,2,Louisana
11,11,Scouts,2nd,35,9,1523,345,3,1,3,Georgia

In [144]:
for i in army.columns.values:
  print(army.groupby(army[i]).max())

         regiment company  deaths  battles  size  veterans  readiness  \
index
0      Nighthawks     1st     523        5  1045         1          1
1      Nighthawks     1st      52       42   957         5          2
2      Nighthawks     2nd      25        2  1099        62          3
3      Nighthawks     2nd     616        2  1400        26          3
4        Dragoons     1st      43        4  1592        73          2
5        Dragoons     1st     234        7  1006        37          1
6        Dragoons     2nd     523        8   987       949          2
7        Dragoons     2nd      62        3   849        48          3
8          Scouts     1st      62        4   973        48          2
9          Scouts     1st      73        7  1005       435          1
10         Scouts     2nd      37        8  1099        63          2
11         Scouts     2nd      35        9  1523       345          3

       armored  deserters      origin
index
0            1          4     Arizona
1            0         24  California
2            1         31       Texas
3            1          2     Florida
4            0          3       Maine
5            1          4        Iowa
6            0         24      Alaska
7            1         31  Washington
8            0          2      Oregon
9            0          3     Wyoming
10           1          2    Louisana
11           1          3     Georgia
            index company  deaths  battles  size  veterans  readiness  \
regiment
Dragoons        7     2nd     523        8  1592       949          3
Nighthawks      3     2nd     616       42  1400        62          3
Scouts         11     2nd      73        9  1523       435          3

            armored  deserters      origin
regiment
Dragoons          1         31  Washington
Nighthawks        1         31       Texas
Scouts            1          3     Wyoming
         index regiment  deaths  battles  size  veterans  readiness  armored  \
company
1st          9   Scouts     523       42  1592       435          2        1
2nd         11   Scouts     616        9  1523       949          3        1

         deserters      origin
company
1st             24     Wyoming
2nd             31  Washington
        index    regiment company  battles  size  veterans  readiness  \
deaths
25          2  Nighthawks     2nd        2  1099        62          3
35         11      Scouts     2nd        9  1523       345          3
37         10      Scouts     2nd        8  1099        63          2
43          4    Dragoons     1st        4  1592        73          2
52          1  Nighthawks     1st       42   957         5          2
62          8      Scouts     2nd        4   973        48          3
73          9      Scouts     1st        7  1005       435          1
234         5    Dragoons     1st        7  1006        37          1
523         6  Nighthawks     2nd        8  1045       949          2
616         3  Nighthawks     2nd        2  1400        26          3

        armored  deserters      origin
deaths
25            1         31       Texas
35            1          3     Georgia
37            1          2    Louisana
43            0          3       Maine
52            0         24  California
62            1         31  Washington
73            0          3     Wyoming
234           1          4        Iowa
523           1         24     Arizona
616           1          2     Florida
         index    regiment company  deaths  size  veterans  readiness  \
battles
2            3  Nighthawks     2nd     616  1400        62          3
3            7    Dragoons     2nd      62   849        48          3
4            8      Scouts     1st      62  1592        73          2
5            0  Nighthawks     1st     523  1045         1          1
7            9      Scouts     1st     234  1006       435          1
8           10      Scouts     2nd     523  1099       949          2
9           11      Scouts     2nd      35  1523       345          3
42           1  Nighthawks     1st      52   957         5          2

         armored  deserters      origin
battles
2              1         31       Texas
3              1         31  Washington
4              0          3      Oregon
5              1          4     Arizona
7              1          4     Wyoming
8              1         24    Louisana
9              1          3     Georgia
42             0         24  California
      index    regiment company  deaths  battles  veterans  readiness  \
size
849       7    Dragoons     2nd      62        3        48          3
957       1  Nighthawks     1st      52       42         5          2
973       8      Scouts     1st      62        4        48          2
987       6    Dragoons     2nd     523        8       949          2
1005      9      Scouts     1st      73        7       435          1
1006      5    Dragoons     1st     234        7        37          1
1045      0  Nighthawks     1st     523        5         1          1
1099     10      Scouts     2nd      37        8        63          3
1400      3  Nighthawks     2nd     616        2        26          3
1523     11      Scouts     2nd      35        9       345          3
1592      4    Dragoons     1st      43        4        73          2

      armored  deserters      origin
size
849         1         31  Washington
957         0         24  California
973         0          2      Oregon
987         0         24      Alaska
1005        0          3     Wyoming
1006        1          4        Iowa
1045        1          4     Arizona
1099        1         31       Texas
1400        1          2     Florida
1523        1          3     Georgia
1592        0          3       Maine
          index    regiment company  deaths  battles  size  readiness  \
veterans
1             0  Nighthawks     1st     523        5  1045          1
5             1  Nighthawks     1st      52       42   957          2
26            3  Nighthawks     2nd     616        2  1400          3
37            5    Dragoons     1st     234        7  1006          1
48            8      Scouts     2nd      62        4   973          3
62            2  Nighthawks     2nd      25        2  1099          3
63           10      Scouts     2nd      37        8  1099          2
73            4    Dragoons     1st      43        4  1592          2
345          11      Scouts     2nd      35        9  1523          3
435           9      Scouts     1st      73        7  1005          1
949           6    Dragoons     2nd     523        8   987          2

          armored  deserters      origin
veterans
1               1          4     Arizona
5               0         24  California
26              1          2     Florida
37              1          4        Iowa
48              1         31  Washington
62              1         31       Texas
63              1          2    Louisana
73              0          3       Maine
345             1          3     Georgia
435             0          3     Wyoming
949             0         24      Alaska
           index regiment company  deaths  battles  size  veterans  armored  \
readiness
1              9   Scouts     1st     523        7  1045       435        1
2             10   Scouts     2nd     523       42  1592       949        1
3             11   Scouts     2nd     616        9  1523       345        1

           deserters      origin
readiness
1                  4     Wyoming
2                 24      Oregon
3                 31  Washington
         index regiment company  deaths  battles  size  veterans  readiness  \
armored
0            9   Scouts     2nd     523       42  1592       949          2
1           11   Scouts     2nd     616        9  1523       345          3

         deserters      origin
armored
0               24     Wyoming
1               31  Washington
           index    regiment company  deaths  battles  size  veterans  \
deserters
2             10      Scouts     2nd     616        8  1400        63
3             11      Scouts     2nd      73        9  1592       435
4              5  Nighthawks     1st     523        7  1045        37
24             6  Nighthawks     2nd     523       42   987       949
31             7  Nighthawks     2nd      62        3  1099        62

           readiness  armored      origin
deserters
2                  3        1      Oregon
3                  3        1     Wyoming
4                  1        1        Iowa
24                 2        0  California
31                 3        1  Washington
            index    regiment company  deaths  battles  size  veterans  \
origin
Alaska          6    Dragoons     2nd     523        8   987       949
Arizona         0  Nighthawks     1st     523        5  1045         1
California      1  Nighthawks     1st      52       42   957         5
Florida         3  Nighthawks     2nd     616        2  1400        26
Georgia        11      Scouts     2nd      35        9  1523       345
Iowa            5    Dragoons     1st     234        7  1006        37
Louisana       10      Scouts     2nd      37        8  1099        63
Maine           4    Dragoons     1st      43        4  1592        73
Oregon          8      Scouts     1st      62        4   973        48
Texas           2  Nighthawks     2nd      25        2  1099        62
Washington      7    Dragoons     2nd      62        3   849        48
Wyoming         9      Scouts     1st      73        7  1005       435

            readiness  armored  deserters
origin
Alaska              2        0         24
Arizona             1        1          4
California          2        0         24
Florida             3        1          2
Georgia             3        1          3
Iowa                1        1          4
Louisana            2        1          2
Maine               2        0          3
Oregon              2        0          2
Texas               3        1         31
Washington          3        1         31
Wyoming             1        0          3

In [159]:

for i in army.columns.values:
  print(i,end = " ")
  print(army[i].dtypes)
  print('Count is ', total_size+1)
  # print(army[i].groupby(army[i]).count()[army[i]])

index int64
regiment object
company object
deaths int64
battles int64
size int64
veterans int64
readiness int64
armored int64
deserters int64
origin object

In [163]:
army.columns

Index(['index', 'regiment', 'company', 'deaths', 'battles', 'size', 'veterans',
       'readiness', 'armored', 'deserters', 'origin'],
      dtype='object')

In [166]:
army.dtypes

index         int64
regiment     object
company      object
deaths        int64
battles       int64
size          int64
veterans      int64
readiness     int64
armored       int64
deserters     int64
origin       object
dtype: object

In [167]:
army.count()

index        12
regiment     12
company      12
deaths       12
battles      12
size         12
veterans     12
readiness    12
armored      12
deserters    12
origin       12
dtype: int64

In [168]:
army.nunique()

index        12
regiment      3
company       2
deaths       10
battles       8
size         11
veterans     11
readiness     3
armored       2
deserters     5
origin       12
dtype: int64

In [169]:
army.columns.to_frame().T

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin

In [170]:
army.dtypes.to_frame().T

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,int64,object,object,int64,int64,int64,int64,int64,int64,int64,object

In [173]:
army.count().to_frame().T

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,12,12,12,12,12,12,12,12,12,12,12

In [174]:
army.nunique().to_frame().T

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,12,3,2,10,8,11,11,3,2,5,12

In [175]:
pd.concat([army.dtypes.to_frame().T
           ,army.count().to_frame().T
           ,army.nunique().to_frame().T])

,index,regiment,company,deaths,battles,size,veterans,readiness,armored,deserters,origin
0,int64,object,object,int64,int64,int64,int64,int64,int64,int64,object
0,12,12,12,12,12,12,12,12,12,12,12
0,12,3,2,10,8,11,11,3,2,5,12